package pl.kti.cp.io.files;

import java.io.*;

import javax.swing.JFileChooser;

public class FileWriterDemo {

	public static void main(String[] args) throws IOException {
		String contents = getContentsFromUser();
		while (true) {
			File file = getFileFromUser();
			if (file != null && !file.exists()) {
				System.out.println("Wrote to file " + file.getAbsolutePath());
				write(contents, file);
				System.out.println("Done.");
				System.exit(0);
			} else {
				System.out.println("Chosen file already exists!");
			}
		}
	}

	private static String getContentsFromUser() throws IOException{
		System.out.println("Please enter the text you would like to write in a file.");
		System.out.println("(Enter a line containing a single \'.\' to end)");
		System.out.println("");

		String line;
		String contents = "";
		String lineSeparator = System.getProperty("line.separator");

		BufferedReader reader = new BufferedReader(new InputStreamReader(System.in));
		
		while ( (line = reader.readLine()) != null){
			if (line.equals(".")){
				reader.close();
				System.out.println("Thank you!");
				return contents;
			}
			contents += line+lineSeparator;
		}
		reader.close();
		return contents;
	}
	private static File getFileFromUser() {
		JFileChooser fileChooser = new JFileChooser();
		fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
		int chosenButton = fileChooser.showDialog(null, "Select");
		if (chosenButton == JFileChooser.CANCEL_OPTION) {
			System.out.println("Bye, bye!!!");
			System.exit(0);
		}
		File file = fileChooser.getSelectedFile();
		return file;
	}

	private static void write(String contents, File file) throws IOException {
		String lineSeparator = System.getProperty("line.separator");
		BufferedWriter writer = new BufferedWriter(new FileWriter(file));
		writer.write("====== Generated by File Writer Demo ======");
		writer.write(lineSeparator);
		writer.write(contents);
		writer.write("============== END ==============");
		writer.write(lineSeparator);
		writer.close();
	}
}